Repository tmax-cloud/hypersds-wiki, pull requests merged in 2021-03, with the labels that each got.

#2 Apply github action
  .github/workflows/assign.yml
  .github/workflows/main.yml
Labels: size/M

#3 Fix github action
  .github/workflows/assign.yml
  .github/workflows/lint.yml
Labels: size/S

#4 Update github action
  .github/workflows/lint.yml
Labels: size/XS

#5 Update github action plugin version
  .github/workflows/lint.yml
Labels: size/XS

#6 Update README
  README.md
Labels: size/M

#1 Add nfs provisioner guide
  .github/workflows/assign.yml
  .github/workflows/lint.yml
  README.md
  nfs/README.md
  nfs/deploy/class.yaml
  nfs/deploy/deployment.yaml
  nfs/deploy/namespace.yaml
  nfs/deploy/rbac.yaml
  nfs/deploy/test-claim.yaml
  nfs/deploy/test-pod.yaml
Labels: documentation, size/L

#7 Add ceph install guide on prolinux
  prolinux_ceph_install_guide/README.md
Labels: documentation, size/L

#8 Add ebs and efs csi guide for aws ec2
  aws_storage_guide/aws_ec2_ebs_efs_csi_guide.docx
Labels: size/XS

#9 Add multipath device ceph install guide
  multipath_device_ceph_install_guide/README.md
  multipath_device_ceph_install_guide/cluster.yaml
  multipath_device_ceph_install_guide/pv-volume.yaml
  multipath_device_ceph_install_guide/sc-local.yaml
Labels: size/L
